## Web Scraping NBA Stats

In [2]:
# import our libraries
import pandas as pd
import requests as re
from bs4 import BeautifulSoup
import time

In [3]:
# store the years we want to scrape for in a list
years = list(range(1991, 2023))

In [5]:
# store the url in a variable
url_start = 'https://www.basketball-reference.com/awards/awards_{}.html'

In [6]:
# download the html from the web pages and write to a file
for year in years:
    url = url_start.format(year)
    data = re.get(url)
    print(f"{year} - {data.status_code}")
    
    with open('mvp/{}.html'.format(year), 'w+',encoding="utf-8") as file:
        file.write(data.text)
        time.sleep(1)

1991 - 200
1992 - 200
1993 - 200
1994 - 200
1995 - 200
1996 - 200
1997 - 200
1998 - 200
1999 - 200
2000 - 200
2001 - 200
2002 - 200
2003 - 200
2004 - 200
2005 - 200
2006 - 200
2007 - 200
2008 - 200
2009 - 200
2010 - 200
2011 - 200
2012 - 200
2013 - 200
2014 - 200
2015 - 200
2016 - 200
2017 - 200
2018 - 200
2019 - 200
2020 - 200
2021 - 200
2022 - 200

In [7]:
# attempt to scrape the data for a single year before scaling up
with open('data/mvp/1991.html', 'r',encoding="utf-8") as f:
    page = f.read()

In [8]:
soup = BeautifulSoup(page)

In [10]:
soup.find('tr', class_='over_header').decompose()

In [11]:
# parse the table using beautiful soup
mvp_table = soup.find(id='mvp')

In [12]:
# read the table with pandas
mvp_1991 = pd.read_html(str(mvp_table))[0]

NumExpr defaulting to 8 threads.

In [13]:
mvp_1991.head()

,Rank,Player,Age,Tm,First,Pts Won,Pts Max,Share,G,MP,PTS,TRB,AST,STL,BLK,FG%,3P%,FT%,WS,WS/48
0,1,Michael Jordan,27,CHI,77.0,891.0,960,0.928,82,37.0,31.5,6.0,5.5,2.7,1.0,0.539,0.312,0.851,20.3,0.321
1,2,Magic Johnson,31,LAL,10.0,497.0,960,0.518,79,37.1,19.4,7.0,12.5,1.3,0.2,0.477,0.320,0.906,15.4,0.251
2,3,David Robinson,25,SAS,6.0,476.0,960,0.496,82,37.7,25.6,13.0,2.5,1.5,3.9,0.552,0.143,0.762,17.0,0.264
3,4,Charles Barkley,27,PHI,2.0,222.0,960,0.231,67,37.3,27.6,10.1,4.2,1.6,0.5,0.570,0.284,0.722,13.4,0.258
4,5,Karl Malone,27,UTA,0.0,142.0,960,0.148,82,40.3,29.0,11.8,3.3,1.1,1.0,0.527,0.286,0.770,15.5,0.225

In [9]:
# writing a loop to run this for all our data
dfs = []
i = 0
for year in years:
    with open('data/mvp/{}.html'.format(year), 'r',encoding="utf-8") as file:
        data = file.read()
    soup = BeautifulSoup(data)
    soup.find('tr', class_='over_header').decompose()
    mvp_table = soup.find(id='mvp')
    mvp = pd.read_html(str(mvp_table))[0]
    mvp['year'] = year
    dfs.append(mvp)

In [10]:
# combine the dataframes in the list
mvps = pd.concat(dfs)

In [11]:
# view the combined dataframe
mvps.head()

,Rank,Player,Age,Tm,First,Pts Won,Pts Max,Share,G,MP,...,TRB,AST,STL,BLK,FG%,3P%,FT%,WS,WS/48,year
0,1,Michael Jordan,27,CHI,77.0,891.0,960,0.928,82,37.0,...,6.0,5.5,2.7,1.0,0.539,0.312,0.851,20.3,0.321,1991
1,2,Magic Johnson,31,LAL,10.0,497.0,960,0.518,79,37.1,...,7.0,12.5,1.3,0.2,0.477,0.320,0.906,15.4,0.251,1991
2,3,David Robinson,25,SAS,6.0,476.0,960,0.496,82,37.7,...,13.0,2.5,1.5,3.9,0.552,0.143,0.762,17.0,0.264,1991
3,4,Charles Barkley,27,PHI,2.0,222.0,960,0.231,67,37.3,...,10.1,4.2,1.6,0.5,0.570,0.284,0.722,13.4,0.258,1991
4,5,Karl Malone,27,UTA,0.0,142.0,960,0.148,82,40.3,...,11.8,3.3,1.1,1.0,0.527,0.286,0.770,15.5,0.225,1991

In [17]:
#save the data in a csv
mvps.to_csv('data/mvps.csv')

## Scraping Player Stats

In [18]:
# store the player stats url in a variable
player_stats_url = "https://www.basketball-reference.com/leagues/NBA_{}_per_game.html"

In [19]:
# download the html for a single year
url = player_stats_url.format(1991)
data = re.get(url)
data.status_code
with open('player/1991.html'.format(year), 'w+',encoding="utf-8") as file:
    file.write(data.text)

The full table data is not saved in the html, we have to use selenium to render the jason that holds the table.

In [20]:
# import webdriver from selenium
from selenium import webdriver

In [21]:
# create a driver object
driver = webdriver.Chrome(executable_path='Users\Abimbola.Balogun\Downloads\chromedriver_win32')

<ipython-input-21-818bbaa49c92>:2: DeprecationWarning: executable_path has been deprecated, please pass in a Service object
  driver = webdriver.Chrome(executable_path='Users\Abimbola.Balogun\Downloads\chromedriver_win32')

In [22]:
# use the driver to render automate a browser and reder the json
year = 1991
url = player_stats_url.format(year)
driver.get(url)
# execute a json script on the automated browser
driver.execute_script("window.scrollTo(1,1000)")
time.sleep(2)
# get the html of the rendered page
html = driver.page_source

In [23]:
with open('player/1991.html'.format(year), 'w+',encoding="utf-8") as file:
    file.write(html)

In [25]:
# get the html for our year range
for year in years:
    url = player_stats_url.format(year)
    driver.get(url)
    driver.execute_script("window.scrollTo(1,1000)")
    time.sleep(2)
    html = driver.page_source
    with open('player/{}.html'.format(year), 'w+',encoding="utf-8") as file:
        file.write(html)

In [26]:
# attempt to scrape the data off a single page before we scale up to the year range
year = 1991

with open('player/{}.html'.format(year), 'r',encoding="utf-8") as file:
    data = file.read()
soup = BeautifulSoup(data)

In [32]:
soup.find('tr',class_='thead').decompose()
stats_table = soup.find(id='per_game_stats')
stats_df = pd.read_html(str(stats_table))[0]
stats_df.head()

,Rk,Player,Pos,Age,Tm,G,GS,MP,FG,FGA,...,FT%,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS
0,1,Alaa Abdelnaby,PF,22,POR,43,0,6.7,1.3,2.7,...,.568,0.6,1.4,2.1,0.3,0.1,0.3,0.5,0.9,3.1
1,2,Mahmoud Abdul-Rauf,PG,21,DEN,67,19,22.5,6.2,15.1,...,.857,0.5,1.3,1.8,3.1,0.8,0.1,1.6,2.2,14.1
2,3,Mark Acres,C,28,ORL,68,0,19.3,1.6,3.1,...,.653,2.1,3.2,5.3,0.4,0.4,0.4,0.6,3.2,4.2
3,4,Michael Adams,PG,28,DEN,66,66,35.5,8.5,21.5,...,.879,0.9,3.0,3.9,10.5,2.2,0.1,3.6,2.5,26.5
4,5,Mark Aguirre,SF,31,DET,78,13,25.7,5.4,11.7,...,.757,1.7,3.1,4.8,1.8,0.6,0.3,1.6,2.7,14.2

In [39]:
# scrape all the stats data from our different html files
stats_list = []
for year in years:
    with open('player/{}.html'.format(year), 'r', encoding='utf-8') as file:
        data = file.read()
    soup = BeautifulSoup(data)
    soup.find('tr', class_='thead').decompose()
    stats_table = soup.find(id='per_game_stats')
    stats_df = pd.read_html(str(stats_table))[0]
    stats_df['year'] = year
    stats_list.append(stats_df)

In [40]:
# combine the data with pandas 
players_df = pd.concat(stats_list)
players_df.columns = [col.lower() for col in players_df.columns]

In [41]:
players_df.sample(10)

,rk,player,pos,age,tm,g,gs,mp,fg,fga,...,orb,drb,trb,ast,stl,blk,tov,pf,pts,year
130,105,Robert Covington,SF,24,PHI,70,49,27.9,4.3,10.8,...,0.9,3.6,4.5,1.5,1.4,0.4,1.8,2.7,13.5,2015
429,Rk,Player,Pos,Age,Tm,G,GS,MP,FG,FGA,...,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS,2006
566,419,Aaron Williams,PF,25,VAN,32,1,17.3,2.6,4.5,...,1.9,2.4,4.3,0.5,0.5,0.8,0.9,2.3,6.2,1997
248,200,Joe Harris,SG,26,BRK,78,14,25.3,3.9,8.0,...,0.7,2.7,3.3,1.6,0.4,0.3,1.2,2.0,10.8,2018
562,441,Mike Wilks,PG,26,SEA,10,0,10.5,1.2,3.1,...,0.3,0.9,1.2,1.4,0.6,0.0,0.9,0.7,4.4,2006
285,Rk,Player,Pos,Age,Tm,G,GS,MP,FG,FGA,...,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS,2005
235,159,Marc Gasol,C,26,MEM,81,81,31.9,4.5,8.5,...,1.9,5.1,7.0,2.5,0.9,1.7,1.8,3.3,11.7,2011
210,168,Fred Hoiberg,SG,26,IND,12,0,7.3,0.5,1.8,...,0.2,0.8,0.9,0.3,0.0,0.0,0.3,0.9,1.6,1999
257,191,Dwight Howard,C,23,ORL,79,79,35.7,7.1,12.4,...,4.3,9.6,13.8,1.4,1.0,2.9,3.0,3.4,20.6,2009
570,441,Jiří Welsch,SG-SF,25,TOT,71,32,18.5,2.1,5.2,...,0.4,2.0,2.4,1.5,0.6,0.1,1.0,1.7,6.5,2005

In [89]:
# save player_stats as csv
players_df.to_csv('data/player_stats.csv')

## Scraping Team Stats

In [42]:
# store the team stats url in a variable
team_url = "https://www.basketball-reference.com/leagues/NBA_{}_standings.html"

In [43]:
# attempt scraping for one year
year = 1991
url = team_url.format(year)

data = re.get(url)
data.status_code

200

In [45]:
# scrape the html for all years and store in a .html file
for year in years:
    url = team_url.format(year)
    data = re.get(url)
    with open(f'team/{year}.html', 'w+', encoding='utf-8') as file:
        file.write(data.text)
    print(f"{year}-{data.status_code}")
    time.sleep(2)

1991-200
1992-200
1993-200
1994-200
1995-200
1996-200
1997-200
1998-200
1999-200
2000-200
2001-200
2002-200
2003-200
2004-200
2005-200
2006-200
2007-200
2008-200
2009-200
2010-200
2011-200
2012-200
2013-200
2014-200
2015-200
2016-200
2017-200
2018-200
2019-200
2020-200
2021-200
2022-200

In [46]:
# scrape the data from a single html file before scaling up
year = 1991
with open('team/{}.html'.format(year), 'r', encoding='utf-8') as file:
    page = file.read()

In [70]:
# scrape eastern confrence stats
soup = BeautifulSoup(page)
soup.find('tr', class_='thead').decompose()
team_stats_E = soup.find(id='divs_standings_E')
team_E_table = pd.read_html(str(team_stats_E))[0]
team_E_table['confrence'] = 'Eastern'
team_E_table['year'] = year
team_E_table.rename(columns={'Eastern Conference':'team'},inplace=True)
team_E_table.head()

,team,W,L,W/L%,GB,PS/G,PA/G,SRS,confrence,year
0,Boston Celtics*,56,26,.683,—,111.5,105.7,5.22,Eastern,1991
1,Philadelphia 76ers*,44,38,.537,12.0,105.4,105.6,-0.39,Eastern,1991
2,New York Knicks*,39,43,.476,17.0,103.1,103.3,-0.43,Eastern,1991
3,Washington Bullets,30,52,.366,26.0,101.4,106.4,-4.84,Eastern,1991
4,New Jersey Nets,26,56,.317,30.0,102.9,107.5,-4.53,Eastern,1991

In [74]:
# scrape western confrence stats
team_stats_W = soup.find(id='divs_standings_W')
team_W_table = pd.read_html(str(team_stats_W))[0]
team_W_table['confrence'] = 'Western'
team_W_table['year'] = year
team_W_table.rename(columns={'Western Conference':'team'},inplace=True)
team_W_table.head()

,team,W,L,W/L%,GB,PS/G,PA/G,SRS,confrence,year
0,Midwest Division,Midwest Division,Midwest Division,Midwest Division,Midwest Division,Midwest Division,Midwest Division,Midwest Division,Western,1991
1,San Antonio Spurs*,55,27,.671,—,107.1,102.6,4.30,Western,1991
2,Utah Jazz*,54,28,.659,1.0,104.0,100.7,3.18,Western,1991
3,Houston Rockets*,52,30,.634,3.0,106.7,103.2,3.27,Western,1991
4,Orlando Magic,31,51,.378,24.0,105.9,109.9,-3.79,Western,1991

In [79]:
# scrape all the team stats data using a loop
team_dfs = []
for year in years:
    with open(f'team/{year}.html','r', encoding='utf-8') as file:
        page = file.read()
    soup = BeautifulSoup(page)
    soup.find('tr',class_='thead').decompose()
    # scrape eastern confrence table
    team_stats = soup.find(id='divs_standings_E')
    team_df = pd.read_html(str(team_stats))[0]
    team_df['year'] = year
    team_df['confrence'] = 'Eastern'
    team_df.rename(columns={'Eastern Conference':'team'},inplace=True)
    team_dfs.append(team_df)
    
    # scrape western confrence table
    team_stats = soup.find(id='divs_standings_W')
    team_df = pd.read_html(str(team_stats))[0]
    team_df['year'] = year
    team_df['confrence'] = 'Western'
    team_df.rename(columns={'Western Conference':'team'},inplace=True)
    team_dfs.append(team_df)

In [88]:
# concats team stats data into a single dateframe
team_stats_df = pd.concat(team_dfs)
team_stats_df.reset_index(inplace=True)
team_stats_df.drop('index',axis=1,inplace=True)
team_stats_df.sample(10)

,team,W,L,W/L%,GB,PS/G,PA/G,SRS,year,confrence
807,Oklahoma City Thunder,45,37,.549,6.0,104.0,101.8,2.47,2015,Western
207,Seattle SuperSonics*,57,25,.695,—,100.9,93.2,6.91,1997,Western
611,New Orleans Hornets*,49,33,.598,5.0,95.8,94.3,1.41,2009,Western
108,Utah Jazz*,53,29,.646,5.0,101.9,97.7,4.10,1994,Western
258,Charlotte Hornets,26,24,.520,7.0,92.9,93.0,0.63,1999,Eastern
254,Indiana Pacers*,33,17,.660,—,94.7,90.9,3.86,1999,Eastern
1063,Memphis Grizzlies*,56,26,.683,—,115.6,109.9,5.37,2022,Western
824,Boston Celtics*,48,34,.585,8.0,105.7,102.5,2.84,2016,Eastern
730,Miami Heat*,66,16,.805,—,102.9,95.0,7.03,2013,Eastern
33,Miami Heat*,38,44,.463,13.0,105.0,109.2,-3.94,1992,Eastern

In [90]:
# save team stats as csv
team_stats_df.to_csv('data/team_stats.csv')